name: polymer_and_dart
description: Sample app built with the polymer.dart package
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  polymer: '>=0.15.1 <0.16.0'
transformers:
- polymer:
    entry_points:
    - web/begin/index.html
    - web/end/index.html
